name: quanty
version: 0.1.0.0
github: "0xgleb/quanty"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

dependencies:
  - base >= 4.14.4.0 && < 5
  - protolude
  - hspec
  - hspec-wai
  - hspec-wai-json
  - servant-server
  - servant
  - servant-openapi3
  - openapi3
  - aeson
  - wai
  - wai-extra
  - wai-cors
  - warp
  - time
  - text
  - bytestring
  - lens
  - erf

language: GHC2024

library:
  source-dirs: src

executables:
  quanty-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quanty

  generate-openapi:
    main: GenerateOpenApi.hs
    source-dirs: app
    ghc-options:
      - -main-is GenerateOpenApi
    dependencies:
      - quanty

tests:
  quanty-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quanty
      - QuickCheck
    build-tools:
      - hspec-discover

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  # Extensions NOT in GHC2024 that we use
  - ApplicativeDo
  - BlockArguments
  - DeriveAnyClass
  - DerivingVia
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - TypeFamilyDependencies
  - ViewPatterns
  # Modern record handling
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedRecordDot
