name: quanty
version: 0.1.0.0
github: "0xgleb/quanty"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

dependencies:
  - base >= 4.14.4.0 && < 5
  - protolude
  - hspec
  - servant-server
  - servant
  - aeson
  - wai
  - warp
  - time
  - text

language: GHC2021

library:
  source-dirs: src

executables:
  quanty-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quanty

tests:
  options-tests:
    main: OptionsPricing.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  # Extensions NOT in GHC2021 that we use
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DerivingVia
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - TypeFamilyDependencies
  - ViewPatterns
  # Modern record handling
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedRecordDot
