name: quanty
version: 0.1.0.0
github: "0xgleb/quanty"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

dependencies:
  - base >= 4.14.4.0 && < 5
  - protolude
  - hspec
  - servant
  - servant-server
  - warp
  - aeson
  - text
  - wai
  - wai-cors

executables:
  quanty-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2

tests:
  options-tests:
    main: OptionsPricing.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - ConstraintKinds
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable # Implies: DeriveFoldable, DeriveFunctor
  - DerivingVia # Implies: DerivingStrategies
  - FlexibleContexts
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoStarIsType
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes # Implies: ExplicitForAll
  - RecordWildCards # Implies: DisambiguateRecordFields
  - ScopedTypeVariables # Implies: ExplicitForAll
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilyDependencies # Implies: TypeFamilies
  - DataKinds
  - KindSignatures
  - PolyKinds
  - TypeOperators
  - ViewPatterns
