name: Format Code

on:
  workflow_dispatch:
  push:
    branches:
      - 'claude/**'

permissions:
  contents: write

jobs:
  format:
    name: Auto-format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Format Haskell code with Fourmolu
        run: |
          nix develop --command fourmolu --mode inplace app/ src/ OptionsPricing.hs || true

      - name: Format Nix code
        run: |
          nix develop --command nixpkgs-fmt *.nix || true

      - name: Format frontend code with Prettier
        run: |
          nix develop --command bash -c "cd frontend && npm ci && npx prettier --write 'src/**/*.{js,ts,svelte,json,css,html}'" || true

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-format code'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
